[FEATURE] Refactor matches
kelostrada/chitczat pull request #27
Opened 2020-09-04 21:09 UTC by agusmoles

I've just removed the index in the db collection as mentioned in this issue: https://github.com/kelostrada/chitczat/issues/3

Anyway I couldn't make `!match` command work since I don't quitely understand the code there and I'm a bit overwhelmed haha. Probably will need some help

2020-09-04 22:39 UTC, kelostrada commented
Okay so I wanted to take #2 and #3 myself, this one is a bit hard and I already have good understanding how to do it, so please let me fight with it ;)

2020-09-04 22:44 UTC, agusmoles commented
That sounds great. Let me know if you need me to explain something of what I've made or whatever, we can make a call 👍

2020-09-04 22:48 UTC, agusmoles commented
@kelostrada oh also I was about to make a ticket to move to `mongoose` maybe instead of using native mongo driver. Anyway didn't work a lot in nodeJS but I think it has some advantages using `mongoose` :+1:

2020-09-04 23:08 UTC, kelostrada commented
I don't think we need to switch to mongoose - why do you think it would help? We don't do very either complicated queries or complicated schemas. I think we better switch to postgres if any, but that's something very low priority

2020-09-05 02:53 UTC, agusmoles commented
Sincerely don't know much so I'll agree with you in this topic! :smile: 👍

2020-09-05 12:27 UTC, kelostrada commented
My guess is for some bigger project it's obvious to use stuff like mongoose or ORM adapters for SQL DBs. But this is so small that we don't need to care ;) Maybe if we were to implement functionalities like handling multiple Slack servers (to distribute this) it would be really required then, but for now I wouldn't worry about that :)

2020-09-05 12:29 UTC, kelostrada commented on src/messages.js
> -  let joined = false;
removing this logic is actually a bug as this is used to check if any user is actually `added`/`joined` or whatever the logic, not if the people array contains any entities

2020-09-05 12:57 UTC, agusmoles commented on src/messages.js
> -  let joined = false;
Isn't it the `added` attribute that we got in the db? Feel free to modify it if something is wrong but I thought this variable was just used to see if some people have joined the queue but we could already check that with the `people.length`

2020-09-05 14:08 UTC, kelostrada commented on src/messages.js
> -  let joined = false;
We actually can't as This would show all the people not just those who joined already

2020-09-05 14:18 UTC, agusmoles commented on src/messages.js
> -  let joined = false;
hmmm I think I am missing something then, could you make the proper change for this?

2020-09-07 23:16 UTC, kelostrada commented on src/users.js
> +const userIsAlreadyAdded = async (userId) => {
more gramatically correct would be `isUserAlreadyAdded` I guess :P

2020-09-07 23:17 UTC, kelostrada commented on src/db.js
> +  return docs;
the object was done for a reason - to make it faster to get users from the collection. But it was a very naive optimisation as the call to db takes probably much longer, so I'm fine with this

2020-09-07 23:18 UTC, agusmoles commented on src/users.js
> +const userIsAlreadyAdded = async (userId) => {
lol agree, missed that :joy:

2020-09-07 23:19 UTC, kelostrada commented on src/matching.js
> +  for (var i = 0; i < count; i++) {
so you build the graph by using indexes from the array but you are not 100% sure the people in the array will always be in the same order.

2020-09-07 23:21 UTC, agusmoles commented on src/matching.js
> +  for (var i = 0; i < count; i++) {
Oh ok I think I got the issue/bug now. I've been investigating a little bit more about the algorithm today and that was my concern... should check a fix for that... 

Do you have something in mind? :thinking:

2020-09-07 23:21 UTC, kelostrada commented on src/matching.js
> +    for (var j = i + 1; j < n; j++) if (g[i][j] == 2) m.push([i, j]);
The built matches should contain IDs of the users so we are sure we saved the matches correctly. What if we delete a record from database? It will break this whole matching system backwards as indexes will change. I intended for this task to switch to using slack IDs as indicators for previous matches so we are 100% sure that we compared the same slack users

2020-09-07 23:23 UTC, agusmoles commented on src/matching.js
> +    for (var j = i + 1; j < n; j++) if (g[i][j] == 2) m.push([i, j]);
Yes, same message than above :+1:

2020-09-07 23:26 UTC, kelostrada commented on src/users.js
> +  if (!userId || !location) return;
This will require the user to provide the location every time which is annoying if you already provided the location before. That's why I wanted to check if the location wasn't provided and just not modify it if user didn't provide it

2020-09-07 23:28 UTC, kelostrada commented on src/matching.js
> +    for (var j = i + 1; j < n; j++) if (g[i][j] == 2) m.push([i, j]);
so I already explain - the matches table in db should contain pairs of slack user IDs. And when you prepare a graph for matching algorithm you want to map all the users to some integer values. And also map the same IDs to the the same integer values in the matches table

2020-09-08 10:18 UTC, kelostrada requested changes
the variables held in `matches` collection in mongo have to be pairs of users IDs. Based on that the matching algorithm has to digest users by IDs, not just indexes in an array.

2020-09-08 21:30 UTC, kelostrada requested changes
some small comments, but great work

2020-09-08 21:30 UTC, kelostrada commented on src/db.js
> +let getPeopleCount = async () => {
this is not used anywhere so let's not introduce this function

2020-09-08 21:30 UTC, kelostrada commented on src/matching.js
> +      const JId = people[j].id;
convention is to use low level case right? so maybe:
```suggestion
      const iID = people[i].id;
      const jID = people[j].id;
```

2020-09-08 21:30 UTC, kelostrada commented on src/matching.js
> +    for (var j = i + 1; j < n; j++) if (g[i][j] == 2) m.push([i, j]);
why not just push the IDs here?

```suggestion
    for (var j = i + 1; j < n; j++) if (g[i][j] == 2) m.push([people[i].id, people[j].id]);
```

2020-09-08 21:30 UTC, kelostrada commented on src/users.js
> +  matches.map((match) => [people[match[0]].id, people[match[1]].id]);
this is not required if you will just push the IDs within `matchPeople` function

2020-09-08 22:08 UTC, kelostrada commented on src/matching.js
> +  let count = people.length;
we could maybe first filter out all the people who didn't join here and it will make it much easier and faster

2020-09-09 11:25 UTC, kelostrada approved these changes

2020-09-09 11:25 UTC, merged